lanuage: python

# download sage
before_install:
  - sudo apt-add-repository -y ppa:aims/sagemath
  - sudo apt-get update -q
  - sudo apt-get install -y sagemath-upstream-binary

# build the code in-place
install:
  - sage setup.py build_ext --inplace

# run the tests
script:
  - sage runtests.py -v
